# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58ebf3175fd66bfa0b43ce535338a5af3b6302263c928917dc8004de6667b44535e9b2d46a547292ac2e089377bc22ea8c89bc19f1429e75b1d39e8b1b7eafc0

test:
  secret_key_base: 88a28326adda6e66189d7da7ac1712397121528564fa405c91f3ea334d785ff86d6d5a1b257f535290c27f4dce625aecef4d00edb199bb90e4bbc81ca4e0cb3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
